DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INT PRIMARY KEY,
    USER_NAME VARCHAR(250) NOT NULL,
    PASSWORD VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS floorplans;

CREATE TABLE floorplans (
    id INT PRIMARY KEY,
    USER_ID INT NOT NULL,
    WIDTH INT NOT NULL,
    HEIGHT INT NOT NULL
);

DROP TABLE IF EXISTS rooms;

CREATE TABLE rooms (
    id INT PRIMARY KEY,
    FLOOR_PLAN_ID INT NOT NULL,
    WIDTH INT NOT NULL,
    HEIGHT INT NOT NULL,
    TOP BIT NOT NULL,
    STARBOARD BIT NOT NULL,
    BOTTOM BIT NOT NULL,
    PORT BIT NOT NULL
);
